### ISSUE TITLE
markdown语法错误导致构建报错

### ISSUE THREAD

**Issue by luoway** [aoligeihi/wiki-now#2]
第一个issue里有markdown语法错误，vitepress解析报错，github issue能展示但也有部分展示异常。
![image](https://github.com/aoligeihi/wiki-now/assets/12523415/15d852f1-2be1-447c-be6a-b3139b894c59)
需要调整issue内容，建议在书写提交前preview，完成格式调整后再提交

**Comment by aoligeihi** [comment]
嗷 原来这样啊,我来来回回删了重新弄搞好几次,我没找到啥问题. 谢谢您哈
